import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    languageOptions: {
      globals: {
        console: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        Promise: "readonly",
        JSON: "readonly",
        Map: "readonly",
        Set: "readonly",
        Symbol: "readonly",
        WeakMap: "readonly",
        WeakSet: "readonly",
        require: "readonly",
        module: "readonly",
        exports: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        process: "readonly",
        Buffer: "readonly",
        global: "readonly",
        window: "readonly",
        document: "readonly",
        navigator: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        alert: "readonly",
      },
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": "warn",
      "no-constant-condition": "error",
      "no-dupe-keys": "error",
      "no-duplicate-case": "error",
      "no-empty": "warn",
      "no-ex-assign": "error",
      "no-extra-boolean-cast": "warn",
      "no-func-assign": "error",
      "no-inner-declarations": "error",
      "no-irregular-whitespace": "warn",
      "no-unreachable": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
      eqeqeq: "warn",
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      "no-self-assign": "error",
      "no-self-compare": "error",
      "no-unused-expressions": "warn",
      "no-useless-return": "warn",
      "no-fallthrough": "warn",
      "no-redeclare": "error",
    },
  },
];
